
import type { Country } from './types';

export const COUNTRIES: Country[] = [
  { name: 'Sverige', flag: '🇸🇪' },
  { name: 'Norge', flag: '🇳🇴' },
  { name: 'Danmark', flag: '🇩🇰' },
  { name: 'Finland', flag: '🇫🇮' },
  { name: 'Island', flag: '🇮🇸' },
  { name: 'Tyskland', flag: '🇩🇪' },
  { name: 'Frankrike', flag: '🇫🇷' },
  { name: 'Italien', flag: '🇮🇹' },
  { name: 'Spanien', flag: '🇪🇸' },
  { name: 'Storbritannien', flag: '🇬🇧' },
  { name: 'USA', flag: '🇺🇸' },
  { name: 'Kanada', flag: '🇨🇦' },
  { name: 'Brasilien', flag: '🇧🇷' },
  { name: 'Argentina', flag: '🇦🇷' },
  { name: 'Japan', flag: '🇯🇵' },
  { name: 'Kina', flag: '🇨🇳' },
  { name: 'Indien', flag: '🇮🇳' },
  { name: 'Australien', flag: '🇦🇺' },
  { name: 'Sydafrika', flag: '🇿🇦' },
  { name: 'Egypten', flag: '🇪🇬' },
  { name: 'Ryssland', flag: '🇷🇺' },
  { name: 'Nederländerna', flag: '🇳🇱' },
  { name: 'Schweiz', flag: '🇨🇭' },
  { name: 'Österrike', flag: '🇦🇹' },
  { name: 'Grekland', flag: '🇬🇷' },
  { name: 'Turkiet', flag: '🇹🇷' },
  { name: 'Mexiko', flag: '🇲🇽' },
  { name: 'Sydkorea', flag: '🇰🇷' },
  { name: 'Nya Zeeland', flag: '🇳🇿' },
  { name: 'Irland', flag: '🇮🇪' },
  { name: 'Portugal', flag: '🇵🇹' },
  { name: 'Belgien', flag: '🇧🇪' },
  { name: 'Polen', flag: '🇵🇱' },
  { name: 'Ukraina', flag: '🇺🇦' }
];
